stages:
  - build
  - deploy
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote
  
jupyter-build:
  stage: build
  image: python:slim
  script:
    - sh install.sh
    - jupyter-book clean .
    - jupyter-book build .
  artifacts:
    paths:
      - _build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
