# in _config.yml
title: "Linear Algebra"
author: "Several authors involved"
only_build_toc_files: true
execute:
  execute_notebooks: "off"
exclude_patterns:
  - '.venv'
parse:
    myst_enable_extensions:
      ## don't forget to list any other extensions you want enabled,
      ## including those that are enabled by default!
      - colon_fence 
      - dollarmath
      - linkify
      - substitution
      - tasklist
      - amsmath
    myst_dmath_double_inline: true
    myst_heading_anchors : 5
sphinx:
  config:
    mathjax3_config: 
      tex:
        macros:
          "N": "\\mathbb{N}"
          "C": "\\mathbb{C}"
          "R": "\\mathbb{R}"
          "ip" : "\\mathbf{\\cdot}"
          "vect": ["\\mathbf{#1}",1]
          "abs": ["\\left\\vert #1 \\right\\vert",1]
          "norm": ["\\left\\Vert #1 \\right\\Vert",1]
          "cp": ["\\times "]
          "nicefrac": ["\\frac "]
          "proj": ["\\operatorname{proj} "]
          "Span": ["\\operatorname{Span}\\left\\lbrace #1 \\right\\rbrace",1]
  local_extensions:
    applet: _ext/
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
    - sphinx_exercise
