# in _config.yml
title: "Linear Algebra"
author: "Dani Balagué Guardia, André Hensbergen, Nikolaas Verhulst, Tom Vroegrijk, and many collaborators."
only_build_toc_files: true

html:
  theme_options:
    use_sidenotes: true
  use_repository_button: true
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
repository:
  url: https://gitlab.ewi.tudelft.nl/dbalague/openlabook
  branch: main

execute:
  execute_notebooks: "off"
exclude_patterns:
  - '.venv'
parse:
    myst_enable_extensions:
      ## don't forget to list any other extensions you want enabled,
      ## including those that are enabled by default!
      - colon_fence 
      - dollarmath
      - linkify
      - substitution
      - tasklist
      - amsmath
    myst_dmath_double_inline: true
    myst_heading_anchors : 5
sphinx:
  config:
    html_static_path: 
      - _static
    language: en
    latex_elements:
          preamble: |
            \usepackage{chemmacros}
            \newcommand{\vect}[1]{\overrightarrow{#1}}
            \newcommand{\N}{\mathbb{N}}
            \newcommand{\R}{\mathbb{R}}
            \newcommand{\C}{\mathbb{C}}
            \newcommand{\ip}{\mathbf{\cdot}}
            \renewcommand{\iff}{\Longleftrightarrow}
            \newcommand{\ce}{\ch}
            \newcommand{\cp}{\times }
            \newcommand{\norm}[1]{\left\Vert{#1}\right\Vert}
            \newcommand{\abs}[1]{\left\vert{#1}\right\vert}
            \renewcommand{\Span}[1]{\operatorname{Span}\left\lbrace#1\right\rbrace}
            \newcommand{\Col}[1]{\ensuremath{{\rm Col\,}{#1}}}
            \newcommand{\Nul}[1]{\ensuremath{{\rm Nul\,}{#1}}}
            \newcommand{\Rank}[1]{\ensuremath{{\rm rank\,}{#1}}}
            \newcommand{\Row}[1]{\ensuremath{{\rm Row\,}{#1}}}
            \newcommand{\Det}[1]{\operatorname{det}\left(#1\right)}
            \renewcommand{\det}[1]{\operatorname{det}\left(#1\right)}
            \renewcommand{\Re}[1]{\operatorname{Re}\left(#1\right)}
            \renewcommand{\Im}[1]{\operatorname{Im}\left(#1\right)}
            \renewcommand{\proj}{\operatorname{proj} }
            \newcommand{\nicefrac}{\frac }
            \newcommand{\mc}{\mathcal}
            \newcommand{\Arg}{\operatorname{Arg}}
            \newcommand{\PB}{P_{\mathcal{B}}}
            \newcommand{\CoBmatrix}[2]{P_{{\mathcal #2}\leftarrow{\mathcal #1}}}
            \usepackage{tabularx}
            \usepackage{threeparttable}
    mathjax3_config: 
      tex:
        inlineMath: [ ['$','$'], ['\(','\)'] ]
        displayMath: [ ['$$','$$'], ['\[','\]'] ]
        macros:
          "CoBmatrix": ["P_{{\\mathcal #2}\\leftarrow{\\mathcal #1}} ",2]
          "mc": "\\mathcal"
          "PB": "P_{\\mathcal B}"
          "N": "\\mathbb{N}"
          "C": "\\mathbb{C}"
          "R": "\\mathbb{R}"
          "ip" : "\\mathbf{\\cdot}"
          "vect": ["\\mathbf{#1}",1]
          "abs": ["\\left\\vert #1 \\right\\vert",1]
          "norm": ["\\left\\Vert #1 \\right\\Vert",1]
          "cp": ["\\times "]
          "Nul": ["\\rm Nul\\, #1", 1]
          "Col": ["\\rm Col\\, #1", 1]
          "Row": ["\\rm Row\\, #1", 1]
          "Rank": ["\\rm rank\\, #1", 1]
          "nicefrac": ["\\frac "]
          "proj": ["\\operatorname{proj} "]
          "Span": ["\\operatorname{Span}\\left\\lbrace #1 \\right\\rbrace",1]
          "Det": ["\\operatorname{det}\\left(#1\\right)",1]
          "Re": ["\\operatorname{Re}\\left(#1\\right)",1]
          "Im": ["\\operatorname{Im}\\left(#1\\right)",1]
  local_extensions:
    applet: _ext/
    htmltable: _ext/
    latextable: _ext/
    review: _ext/
    parentheses_list: _ext/
    latexlist: _ext/
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
    - sphinx_exercise
    - sphinx.ext.imgconverter

latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true